//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PfcDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dieta
    {
        public int Id { get; set; }
        public string Descripcio { get; set; }
        public int NomUsuari { get; set; }
        public System.DateTime Data { get; set; }
        public decimal Import { get; set; }
        public int Tipus { get; set; }
        public int Estat { get; set; }
    
        public virtual EstatDieta EstatDieta { get; set; }
        public virtual TipusDieta TipusDieta { get; set; }
        public virtual Usuari Usuari { get; set; }
    }
}
