//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PfcDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PfcEntities : DbContext
    {
        public PfcEntities()
            : base("name=PfcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contrasenya> Contrasenya { get; set; }
        public virtual DbSet<Dieta> Dieta { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<EstatDieta> EstatDieta { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<TipusDieta> TipusDieta { get; set; }
        public virtual DbSet<Usuari> Usuari { get; set; }
    }
}
